version: "3.9"

services:
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://tranquocdong102_db_user:pdtYMdQKBnU1Puoz@cluster0.6b6ulrh.mongodb.net/basic_mern_db
    volumes:
      - ./backend:/app
      - /app/node_modules
      
  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend