version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/mern-backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8081
      - MONGO_URI=${MONGO_URI}
    expose:
      - "8081"

  frontend:
    image: ${DOCKERHUB_USERNAME}/mern-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80" 
